# Generated by Django 5.1.4 on 2024-12-11 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='course_year',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='specialty',
        ),
    ]
